# Generated by Django 5.2.8 on 2025-11-20 03:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peserta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nis', models.CharField(max_length=20)),
                ('nama', models.CharField(max_length=100)),
                ('kelas', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ujian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_ujian', models.CharField(max_length=100)),
                ('pin_ujian', models.CharField(max_length=10)),
                ('url_soal', models.URLField()),
                ('waktu_mulai', models.DateTimeField()),
                ('durasi', models.IntegerField()),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='KodeAkses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kode', models.CharField(max_length=50, unique=True)),
                ('terpakai', models.BooleanField(default=False)),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian_core.ujian')),
            ],
        ),
        migrations.CreateModel(
            name='HasilUjian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jawaban', models.JSONField(default=dict)),
                ('percobaan_keluar', models.IntegerField(default=0)),
                ('waktu_mulai', models.DateTimeField(auto_now_add=True)),
                ('waktu_selesai', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('mulai', 'Mulai'), ('selesai', 'Selesai'), ('diskualifikasi', 'Diskualifikasi')], default='mulai', max_length=20)),
                ('peserta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian_core.peserta')),
                ('ujian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ujian_core.ujian')),
            ],
        ),
    ]
